services:
  postgres:
    image: postgres:16-alpine
    profiles:
      - prod
      - local
      - dev
    container_name: tech-lab-postgres
    environment:
      POSTGRES_DB: techlab
      POSTGRES_USER: techlab
      POSTGRES_PASSWORD: techlab
    ports:
      - "5432:5432"
    volumes:
      - tech-lab-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    image: eduardo2626/techlab-frontend:latest
    profiles:
      - prod
    container_name: tech-lab-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
      DATABASE_URL: postgres://techlab:techlab@postgres:5432/techlab
    depends_on:
      - postgres
    restart: unless-stopped

  app-local:
    profiles:
      - local
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tech-lab-app-local
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
      DATABASE_URL: postgres://techlab:techlab@postgres:5432/techlab
    depends_on:
      - postgres
    restart: unless-stopped

  app-dev:
    profiles:
      - dev
    image: node:20-alpine
    container_name: tech-lab-dev
    working_dir: /app
    command: sh -c "npm ci && npm run dev -- -H 0.0.0.0 -p 3000"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: "1"
      DATABASE_URL: postgres://techlab:techlab@postgres:5432/techlab
    depends_on:
      - postgres

volumes:
  tech-lab-postgres-data:
